# Generated by Django 5.0.3 on 2024-06-13 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory_name',
        ),
    ]
